### ISSUE TITLE
myAPP and myApp name collision on Mac

### ISSUE THREAD

**Issue by chunhualiao** [RaceDetectionService/RaceDetectionService_Server#7]
Here is what I got when cloning this repo on  a Mac OS X machine. 
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tools_output/dataRaceTest1/myAPP'
  'tools_output/dataRaceTest1/myApp'
```

Please rename one of them to avoid this problem on mac.

**Comment by ouankou** [comment]
`myAPP` is removed in the commit https://github.com/RaceDetectionService/RaceDetectionService_Server/commit/5d8a870246bb75254e30b9e4f6860436a30d3303.

Now the code can be cloned to macOS correctly.
