### ISSUE TITLE
readme.md refers to passlab's wiki

### ISSUE THREAD

**Issue by chunhualiao** [RaceDetectionService/RaceDetectionService_Server#8]
https://github.com/RaceDetectionService/RaceDetectionService_Server/blob/master/src/README.md

Our goal is to move everything about RDS into https://github.com/RaceDetectionService/RaceDetectionService_Server 

Can you check if this readme.md should be updated or removed?

**Comment by ouankou** [comment]
The README and its cited wiki page are updated.
